// Comprehensive Football Historic Word Gap Dataset (120+ Curated Historic Words)
const SEED_WORDS = [
  // 1. WORLD CUP LEGENDS & BALLON D'OR ICONS
  {
    word: 'MARADONA',
    category: 'World Cup Legends',
    clue: 'Argentina 1986 icon who scored the Hand of God and Goal of the Century against England.',
    masked_pattern: 'M _ R _ D _ N A',
    missing_letters: 'A,A,O',
    distractors: 'E,K,U,S',
    year: '1986',
    team: 'Argentina',
    difficulty: 2
  },
  {
    word: 'ZIDANE',
    category: 'World Cup Legends',
    clue: 'French number 10 who scored two headers in the 1998 final and struck the famous Glasgow volley.',
    masked_pattern: 'Z _ D _ N E',
    missing_letters: 'I,A',
    distractors: 'O,E,R,T',
    year: '1998',
    team: 'France',
    difficulty: 1
  },
  {
    word: 'CRUYFF',
    category: 'World Cup Legends',
    clue: 'Dutch master of Total Football famous for his 1974 dummy turn and Barcelona legacy.',
    masked_pattern: 'C R _ Y _ F',
    missing_letters: 'U,F',
    distractors: 'O,E,T,K',
    year: '1974',
    team: 'Netherlands',
    difficulty: 2
  },
  {
    word: 'PELE',
    category: 'World Cup Legends',
    clue: 'The King of Football who won three World Cups and scored in the 1958 final at just 17.',
    masked_pattern: 'P _ L _',
    missing_letters: 'E,E',
    distractors: 'A,O,I,U',
    year: '1958',
    team: 'Brazil',
    difficulty: 1
  },
  {
    word: 'MESSI',
    category: 'World Cup Legends',
    clue: '8-time Ballon d\'Or winner who captained Argentina to glory at the 2022 World Cup in Qatar.',
    masked_pattern: 'M _ S _ I',
    missing_letters: 'E,S',
    distractors: 'A,T,R,O',
    year: '2022',
    team: 'Argentina',
    difficulty: 1
  },
  {
    word: 'RONALDO',
    category: 'World Cup Legends',
    clue: 'O Fenomeno, Brazil striker who overcame knee surgery to score twice in the 2002 World Cup final.',
    masked_pattern: 'R _ N _ L D _',
    missing_letters: 'O,A,O',
    distractors: 'E,I,U,S',
    year: '2002',
    team: 'Brazil',
    difficulty: 2
  },
  {
    word: 'BAGGIO',
    category: 'World Cup Legends',
    clue: 'The Divine Ponytail, Italian Ballon d\'Or winner whose 1994 penalty heartbreak silenced Pasadena.',
    masked_pattern: 'B _ G G _ O',
    missing_letters: 'A,I',
    distractors: 'E,O,R,U',
    year: '1994',
    team: 'Italy',
    difficulty: 2
  },
  {
    word: 'BECKENBAUER',
    category: 'World Cup Legends',
    clue: 'Der Kaiser, revolutionary German sweeper who won the World Cup as both captain and manager.',
    masked_pattern: 'B _ C K _ N B _ U E R',
    missing_letters: 'E,E,A',
    distractors: 'I,O,T,S',
    year: '1974',
    team: 'West Germany',
    difficulty: 3
  },
  {
    word: 'YASHIN',
    category: 'World Cup Legends',
    clue: 'The Black Spider of Dynamo Moscow, the only goalkeeper in history to win the Ballon d\'Or.',
    masked_pattern: 'Y _ S H _ N',
    missing_letters: 'A,I',
    distractors: 'E,O,T,K',
    year: '1963',
    team: 'Soviet Union',
    difficulty: 2
  },
  {
    word: 'CHARLTON',
    category: 'World Cup Legends',
    clue: 'Munich air disaster survivor and midfield powerhouse who guided England to the 1966 World Cup.',
    masked_pattern: 'C H _ R L T _ N',
    missing_letters: 'A,O',
    distractors: 'E,I,U,S',
    year: '1966',
    team: 'England',
    difficulty: 2
  },
  {
    word: 'PUSKAS',
    category: 'World Cup Legends',
    clue: 'The Galloping Major who led Hungary\'s Mighty Magyars and has FIFA\'s best goal award named after him.',
    masked_pattern: 'P _ S K _ S',
    missing_letters: 'U,A',
    distractors: 'O,E,I,T',
    year: '1954',
    team: 'Hungary',
    difficulty: 2
  },
  {
    word: 'EUSEBIO',
    category: 'World Cup Legends',
    clue: 'The Black Panther of Mozambique and Benfica who scored 9 goals at the 1966 World Cup.',
    masked_pattern: 'E _ S E B _ O',
    missing_letters: 'U,I',
    distractors: 'A,O,R,T',
    year: '1966',
    team: 'Portugal',
    difficulty: 2
  },
  {
    word: 'GULLIT',
    category: 'World Cup Legends',
    clue: 'Dreadlocked Dutch captain who led the Netherlands to Euro 1988 glory with a soaring header.',
    masked_pattern: 'G _ L L _ T',
    missing_letters: 'U,I',
    distractors: 'O,E,A,S',
    year: '1988',
    team: 'Netherlands',
    difficulty: 2
  },
  {
    word: 'MALDINI',
    category: 'World Cup Legends',
    clue: 'Milan legendary number 3 defender who played in four World Cups across three decades.',
    masked_pattern: 'M _ L D _ N I',
    missing_letters: 'A,I',
    distractors: 'E,O,R,T',
    year: '1994',
    team: 'Italy',
    difficulty: 2
  },
  {
    word: 'MBAPPE',
    category: 'World Cup Legends',
    clue: 'French dynamo who scored a sensational hat-trick in the 2022 World Cup final in Qatar.',
    masked_pattern: 'M B _ P P _',
    missing_letters: 'A,E',
    distractors: 'O,I,U,T',
    year: '2022',
    team: 'France',
    difficulty: 1
  },
  {
    word: 'INIESTA',
    category: 'World Cup Legends',
    clue: 'Midfield maestro who netted the 116th-minute World Cup winning goal for Spain in Johannesburg.',
    masked_pattern: 'I N _ _ S T A',
    missing_letters: 'I,E',
    distractors: 'A,O,U,R',
    year: '2010',
    team: 'Spain',
    difficulty: 1
  },
  {
    word: 'ROMARIO',
    category: 'World Cup Legends',
    clue: 'Toe-poke specialist and penalty-box predator who propelled Brazil to the 1994 World Cup trophy.',
    masked_pattern: 'R _ M _ R I O',
    missing_letters: 'O,A',
    distractors: 'E,I,U,S',
    year: '1994',
    team: 'Brazil',
    difficulty: 2
  },
  {
    word: 'MATTHAUS',
    category: 'World Cup Legends',
    clue: 'West German captain who lifted the 1990 World Cup and played in a record 5 tournaments.',
    masked_pattern: 'M _ T T H _ U S',
    missing_letters: 'A,A',
    distractors: 'E,O,I,R',
    year: '1990',
    team: 'West Germany',
    difficulty: 3
  },
  {
    word: 'KAKA',
    category: 'World Cup Legends',
    clue: 'Gliding Brazilian playmaker who won the 2007 Ballon d\'Or and the 2002 World Cup.',
    masked_pattern: 'K _ K _',
    missing_letters: 'A,A',
    distractors: 'O,E,I,U',
    year: '2007',
    team: 'Brazil',
    difficulty: 1
  },
  {
    word: 'PLATINI',
    category: 'World Cup Legends',
    clue: 'French maestro who scored an astonishing 9 goals in 5 games at Euro 1984.',
    masked_pattern: 'P L _ T _ N I',
    missing_letters: 'A,I',
    distractors: 'E,O,U,S',
    year: '1984',
    team: 'France',
    difficulty: 2
  },

  // 2. HISTORIC STADIUMS & TEMPLES OF FOOTBALL
  {
    word: 'WEMBLEY',
    category: 'Historic Stadiums',
    clue: 'The cathedral of English football with the famous Twin Towers where the 1966 World Cup was won.',
    masked_pattern: 'W _ M B _ E Y',
    missing_letters: 'E,L',
    distractors: 'A,R,T,O',
    year: '1966',
    team: 'London, England',
    difficulty: 1
  },
  {
    word: 'MARACANA',
    category: 'Historic Stadiums',
    clue: 'Colossal Rio stadium that held 200,000 spectators for the heartbreaking 1950 Maracanazo final.',
    masked_pattern: 'M _ R _ C _ N A',
    missing_letters: 'A,A,A',
    distractors: 'E,O,I,U',
    year: '1950',
    team: 'Rio de Janeiro, Brazil',
    difficulty: 2
  },
  {
    word: 'BERNABEU',
    category: 'Historic Stadiums',
    clue: 'Gleaming fortress in Madrid named after the legendary president who created the European Cup dynasty.',
    masked_pattern: 'B _ R N _ B _ U',
    missing_letters: 'E,A,E',
    distractors: 'I,O,T,S',
    year: '1947',
    team: 'Real Madrid',
    difficulty: 2
  },
  {
    word: 'CAMP NOU',
    category: 'Historic Stadiums',
    clue: 'Europe\'s largest football cathedral where 1999 Treble stoppage time and 2017 Remontada occurred.',
    masked_pattern: 'C _ M P  N _ U',
    missing_letters: 'A,O',
    distractors: 'E,I,U,R',
    year: '1957',
    team: 'FC Barcelona',
    difficulty: 1
  },
  {
    word: 'SAN SIRO',
    category: 'Historic Stadiums',
    clue: 'Historic Milan amphitheater shared by AC Milan and Inter, officially named Stadio Giuseppe Meazza.',
    masked_pattern: 'S _ N  S _ R O',
    missing_letters: 'A,I',
    distractors: 'E,O,U,T',
    year: '1926',
    team: 'Milan, Italy',
    difficulty: 1
  },
  {
    word: 'ANFIELD',
    category: 'Historic Stadiums',
    clue: 'Famous Merseyside stadium where The Kop roars You\'ll Never Walk Alone before European nights.',
    masked_pattern: 'A N F _ _ L D',
    missing_letters: 'I,E',
    distractors: 'O,A,R,T',
    year: '1884',
    team: 'Liverpool FC',
    difficulty: 1
  },
  {
    word: 'OLD TRAFFORD',
    category: 'Historic Stadiums',
    clue: 'Sir Bobby Charlton dubbed this Manchester ground The Theatre of Dreams.',
    masked_pattern: 'O L D  T R _ F F _ R D',
    missing_letters: 'A,O',
    distractors: 'E,I,U,S',
    year: '1910',
    team: 'Manchester United',
    difficulty: 2
  },
  {
    word: 'AZTECA',
    category: 'Historic Stadiums',
    clue: 'Mexico City ground that hosted two World Cup finals (1970 Pelé and 1986 Maradona).',
    masked_pattern: 'A Z T _ C _',
    missing_letters: 'E,A',
    distractors: 'I,O,U,R',
    year: '1970',
    team: 'Mexico City',
    difficulty: 2
  },
  {
    word: 'BOMBONERA',
    category: 'Historic Stadiums',
    clue: 'The Chocolate Box in Buenos Aires famous for its vibrating stands when Boca Juniors fans chant.',
    masked_pattern: 'B _ M B _ N E R _',
    missing_letters: 'O,O,A',
    distractors: 'E,I,U,T',
    year: '1940',
    team: 'Boca Juniors',
    difficulty: 3
  },
  {
    word: 'HIGHBURY',
    category: 'Historic Stadiums',
    clue: 'Arsenal\'s beloved Art Deco home where the Invincibles went unbeaten through 2003-04.',
    masked_pattern: 'H _ G H B _ R Y',
    missing_letters: 'I,U',
    distractors: 'A,E,O,T',
    year: '2004',
    team: 'Arsenal',
    difficulty: 2
  },

  // 3. CHAMPIONS LEAGUE & EUROPEAN MIRACLES
  {
    word: 'GERRARD',
    category: 'Champions League Miracles',
    clue: 'Captain fantastic whose looping header sparked Liverpool\'s 3-goal comeback in the 2005 Istanbul final.',
    masked_pattern: 'G _ R R _ R D',
    missing_letters: 'E,A',
    distractors: 'O,I,U,T',
    year: '2005',
    team: 'Liverpool',
    difficulty: 1
  },
  {
    word: 'SOLSKJAER',
    category: 'Champions League Miracles',
    clue: 'Super sub who extended his right boot in the 93rd minute at Camp Nou to win the 1999 Treble.',
    masked_pattern: 'S _ L S K _ _ E R',
    missing_letters: 'O,J,A',
    distractors: 'E,I,T,U',
    year: '1999',
    team: 'Manchester United',
    difficulty: 3
  },
  {
    word: 'DROGBA',
    category: 'Champions League Miracles',
    clue: 'Ivorian hero who equalized with a bullet header and tucked the decisive penalty in Munich 2012.',
    masked_pattern: 'D R _ G _ A',
    missing_letters: 'O,B',
    distractors: 'E,A,T,K',
    year: '2012',
    team: 'Chelsea',
    difficulty: 1
  },
  {
    word: 'LEVERKUSEN',
    category: 'Champions League Miracles',
    clue: 'German finalist stunned by Zidane\'s left-foot volley at Hampden Park in 2002.',
    masked_pattern: 'L _ V E R K _ S E N',
    missing_letters: 'E,U',
    distractors: 'A,O,I,T',
    year: '2002',
    team: 'Germany',
    difficulty: 2
  },
  {
    word: 'REMONTADA',
    category: 'Champions League Miracles',
    clue: 'Spanish word for comeback, forever linked to Barcelona overturning a 4-0 deficit against PSG.',
    masked_pattern: 'R _ M O N T _ D A',
    missing_letters: 'E,A',
    distractors: 'I,O,U,S',
    year: '2017',
    team: 'Barcelona',
    difficulty: 2
  },
  {
    word: 'DUDEK',
    category: 'Champions League Miracles',
    clue: 'Polish keeper whose Grobbelaar-inspired spaghetti legs hypnotized Milan shooters in Istanbul.',
    masked_pattern: 'D _ D _ K',
    missing_letters: 'U,E',
    distractors: 'A,O,I,T',
    year: '2005',
    team: 'Liverpool',
    difficulty: 1
  },
  {
    word: 'ORIGI',
    category: 'Champions League Miracles',
    clue: 'Belgian striker who finished the famous corner taken quickly against Barcelona in 2019.',
    masked_pattern: 'O R _ G _',
    missing_letters: 'I,I',
    distractors: 'A,E,U,T',
    year: '2019',
    team: 'Liverpool',
    difficulty: 1
  },
  {
    word: 'NEUER',
    category: 'Champions League Miracles',
    clue: 'German sweeper-keeper giant who captained Bayern Munich to historic Champions League trebles.',
    masked_pattern: 'N _ _ E R',
    missing_letters: 'E,U',
    distractors: 'A,O,I,T',
    year: '2013',
    team: 'Bayern Munich',
    difficulty: 1
  },
  {
    word: 'MOURINHO',
    category: 'Champions League Miracles',
    clue: 'The Special One who guided Porto (2004) and Inter (2010) to miraculous Champions League titles.',
    masked_pattern: 'M _ U R _ N H O',
    missing_letters: 'O,I',
    distractors: 'A,E,T,S',
    year: '2004',
    team: 'Porto / Inter',
    difficulty: 2
  },
  {
    word: 'GUARDIOLA',
    category: 'Champions League Miracles',
    clue: 'Tactical mastermind who built the Barcelona sextuple team and guided Man City to the 2023 treble.',
    masked_pattern: 'G _ A R D _ O L A',
    missing_letters: 'U,I',
    distractors: 'E,O,A,T',
    year: '2009',
    team: 'Barcelona / Man City',
    difficulty: 2
  },

  // 4. TACTICS, SKILLS & FOOTBALL RULES
  {
    word: 'PANENKA',
    category: 'Tactics & Iconic Plays',
    clue: 'Chipped penalty down the center pioneered by Antonin Panenka in the Euro 1976 shootout.',
    masked_pattern: 'P _ N _ N K A',
    missing_letters: 'A,E',
    distractors: 'O,I,U,T',
    year: '1976',
    team: 'Czechoslovakia',
    difficulty: 2
  },
  {
    word: 'RABONA',
    category: 'Tactics & Iconic Plays',
    clue: 'Flamboyant kicking technique where a player wraps their striking leg behind their standing leg.',
    masked_pattern: 'R _ B _ N A',
    missing_letters: 'A,O',
    distractors: 'E,I,U,S',
    year: 'Skill',
    team: 'Football Skill',
    difficulty: 2
  },
  {
    word: 'NUTMEG',
    category: 'Tactics & Iconic Plays',
    clue: 'Audacious street skill of kicking the ball through an opponent\'s open legs.',
    masked_pattern: 'N _ T M _ G',
    missing_letters: 'U,E',
    distractors: 'A,O,I,R',
    year: 'Skill',
    team: 'Football Skill',
    difficulty: 1
  },
  {
    word: 'VOLLEY',
    category: 'Tactics & Iconic Plays',
    clue: 'Striking the ball directly out of the air before it makes contact with the ground.',
    masked_pattern: 'V _ L L _ Y',
    missing_letters: 'O,E',
    distractors: 'A,I,U,T',
    year: 'Play',
    team: 'Technique',
    difficulty: 1
  },
  {
    word: 'OFFSIDE',
    category: 'Tactics & Iconic Plays',
    clue: 'Law 11 infraction when an attacker is nearer to the opponent\'s goal line than the ball and second-last opponent.',
    masked_pattern: 'O F F _ _ D E',
    missing_letters: 'S,I',
    distractors: 'A,E,O,T',
    year: 'Rule',
    team: 'Laws of the Game',
    difficulty: 1
  },
  {
    word: 'TIKI TAKA',
    category: 'Tactics & Iconic Plays',
    clue: 'Style of play characterized by short passing and movement, championed by Spain and Barcelona.',
    masked_pattern: 'T _ K I  T _ K A',
    missing_letters: 'I,A',
    distractors: 'E,O,U,R',
    year: '2008',
    team: 'Spain / Barcelona',
    difficulty: 1
  },
  {
    word: 'CATENACCIO',
    category: 'Tactics & Iconic Plays',
    clue: 'Italian tactical system emphasizing a deep defensive line, door-bolt marking, and a free sweeper.',
    masked_pattern: 'C _ T E N _ C C _ O',
    missing_letters: 'A,A,I',
    distractors: 'E,O,U,T',
    year: '1960',
    team: 'Inter Milan / Italy',
    difficulty: 3
  },
  {
    word: 'GEGENPRESS',
    category: 'Tactics & Iconic Plays',
    clue: 'German counter-pressing system popularized by Jurgen Klopp where a team presses immediately upon losing the ball.',
    masked_pattern: 'G _ G E N P R _ S S',
    missing_letters: 'E,E',
    distractors: 'A,O,I,U',
    year: '2011',
    team: 'Dortmund / Liverpool',
    difficulty: 2
  },
  {
    word: 'HAT TRICK',
    category: 'Tactics & Iconic Plays',
    clue: 'Scoring three goals in a single match by an individual player.',
    masked_pattern: 'H _ T  T R _ C K',
    missing_letters: 'A,I',
    distractors: 'E,O,U,S',
    year: 'Term',
    team: 'Football Term',
    difficulty: 1
  },
  {
    word: 'CLEAN SHEET',
    category: 'Tactics & Iconic Plays',
    clue: 'Goalkeeper and defense finishing a full match without conceding a single goal.',
    masked_pattern: 'C L _ _ N  S H E E T',
    missing_letters: 'E,A',
    distractors: 'O,I,U,R',
    year: 'Term',
    team: 'Goalkeeping',
    difficulty: 2
  },

  // 5. HISTORIC UNDERDOGS & FAIRYTALES
  {
    word: 'LEICESTER',
    category: 'Underdogs & Fairytales',
    clue: 'The 5,000-to-1 outsiders who defied all probability to win the 2015-16 English Premier League.',
    masked_pattern: 'L _ I C _ S T _ R',
    missing_letters: 'E,E,E',
    distractors: 'A,O,U,T',
    year: '2016',
    team: 'Leicester City',
    difficulty: 2
  },
  {
    word: 'CHARISTEAS',
    category: 'Underdogs & Fairytales',
    clue: 'Greek striker who headed the winning goal against Portugal in Lisbon to win Euro 2004.',
    masked_pattern: 'C H _ R _ S T _ A S',
    missing_letters: 'A,I,E',
    distractors: 'O,U,T,K',
    year: '2004',
    team: 'Greece',
    difficulty: 3
  },
  {
    word: 'DENMARK',
    category: 'Underdogs & Fairytales',
    clue: 'Called off the beach as late replacements for Yugoslavia, they sensationally won Euro 1992.',
    masked_pattern: 'D _ N M _ R K',
    missing_letters: 'E,A',
    distractors: 'O,I,U,S',
    year: '1992',
    team: 'Denmark',
    difficulty: 1
  },
  {
    word: 'SENEGAL',
    category: 'Underdogs & Fairytales',
    clue: 'African debutants who shocked reigning world champions France 1-0 in the 2002 World Cup opener.',
    masked_pattern: 'S _ N _ G A L',
    missing_letters: 'E,E',
    distractors: 'A,O,I,U',
    year: '2002',
    team: 'Senegal',
    difficulty: 2
  },
  {
    word: 'CAMEROON',
    category: 'Underdogs & Fairytales',
    clue: 'Roger Milla\'s corner-flag dancing Indomitable Lions who stunned Argentina at Italia 90.',
    masked_pattern: 'C _ M E R _ _ N',
    missing_letters: 'A,O,O',
    distractors: 'E,I,U,T',
    year: '1990',
    team: 'Cameroon',
    difficulty: 2
  },
  {
    word: 'CROATIA',
    category: 'Underdogs & Fairytales',
    clue: 'Checkerboard nation led by Luka Modric who reached the 2018 World Cup final with just 4 million citizens.',
    masked_pattern: 'C R _ _ T I A',
    missing_letters: 'O,A',
    distractors: 'E,I,U,S',
    year: '2018',
    team: 'Croatia',
    difficulty: 1
  },

  // 6. TROPHIES, AWARDS & ICONIC TITLES
  {
    word: 'JULES RIMET',
    category: 'Trophies & Awards',
    clue: 'Original gold trophy featuring Nike the goddess of victory, permanently retained by Brazil in 1970.',
    masked_pattern: 'J _ L E S  R _ M E T',
    missing_letters: 'U,I',
    distractors: 'A,O,E,T',
    year: '1930',
    team: 'World Cup Trophy',
    difficulty: 2
  },
  {
    word: 'BALLON DOR',
    category: 'Trophies & Awards',
    clue: 'Prestigious golden ball trophy presented annually by France Football to the world\'s best player.',
    masked_pattern: 'B _ L L _ N  D O R',
    missing_letters: 'A,O',
    distractors: 'E,I,U,T',
    year: '1956',
    team: 'Global Award',
    difficulty: 1
  },
  {
    word: 'GOLDEN BOOT',
    category: 'Trophies & Awards',
    clue: 'Award bestowed upon the highest individual goalscorer at the FIFA World Cup finals.',
    masked_pattern: 'G _ L D _ N  B O O T',
    missing_letters: 'O,E',
    distractors: 'A,I,U,R',
    year: 'Award',
    team: 'FIFA Trophy',
    difficulty: 1
  },
  {
    word: 'LIBERTADORES',
    category: 'Trophies & Awards',
    clue: 'The supreme club championship of South American football, named after the leaders of independence.',
    masked_pattern: 'L _ B E R T _ D O R _ S',
    missing_letters: 'I,A,E',
    distractors: 'O,U,T,S',
    year: '1960',
    team: 'CONMEBOL',
    difficulty: 3
  },

  // 7. MORE LEGENDS & BALLON D'OR WINNERS
  {
    word: 'ZICO',
    category: 'World Cup Legends',
    clue: 'The White Pelé, free-kick wizard who conducted Brazil\'s mesmerizing 1982 World Cup midfield.',
    masked_pattern: 'Z _ C _',
    missing_letters: 'I,O',
    distractors: 'A,E,U,K',
    year: '1982',
    team: 'Brazil / Flamengo',
    difficulty: 1
  },
  {
    word: 'GARRINCHA',
    category: 'World Cup Legends',
    clue: 'The Joy of the People, bent-legged dribbling genius who carried Brazil to the 1962 World Cup title.',
    masked_pattern: 'G _ R R _ N C H _',
    missing_letters: 'A,I,A',
    distractors: 'E,O,U,T',
    year: '1962',
    team: 'Brazil / Botafogo',
    difficulty: 3
  },
  {
    word: 'RIVALDO',
    category: 'World Cup Legends',
    clue: 'Left-footed magician who scored in five consecutive matches during Brazil\'s 2002 World Cup victory.',
    masked_pattern: 'R _ V _ L D O',
    missing_letters: 'I,A',
    distractors: 'E,O,U,T',
    year: '2002',
    team: 'Brazil / Barcelona',
    difficulty: 2
  },
  {
    word: 'FIGO',
    category: 'World Cup Legends',
    clue: 'Portuguese winger and 2000 Ballon d\'Or winner whose controversial transfer to Real Madrid sparked a Clásico storm.',
    masked_pattern: 'F _ G _',
    missing_letters: 'I,O',
    distractors: 'A,E,U,R',
    year: '2000',
    team: 'Portugal / Real Madrid',
    difficulty: 1
  },
  {
    word: 'RAUL',
    category: 'Champions League Miracles',
    clue: 'El Ferrari of Real Madrid who scored in the 2000 and 2002 UCL finals and shushed the Camp Nou crowd.',
    masked_pattern: 'R _ _ L',
    missing_letters: 'A,U',
    distractors: 'O,E,I,T',
    year: '2000',
    team: 'Real Madrid',
    difficulty: 1
  },
  {
    word: 'CASILLAS',
    category: 'World Cup Legends',
    clue: 'San Iker, Spanish goalkeeper captain who denied Robben in the 2010 World Cup final with his toe.',
    masked_pattern: 'C _ S _ L L _ S',
    missing_letters: 'A,I,A',
    distractors: 'E,O,U,T',
    year: '2010',
    team: 'Spain / Real Madrid',
    difficulty: 2
  },
  {
    word: 'PIRLO',
    category: 'World Cup Legends',
    clue: 'The Architect, deep-lying Italian playmaker who assisted Grosso in the 2006 World Cup semifinal.',
    masked_pattern: 'P _ R L _',
    missing_letters: 'I,O',
    distractors: 'A,E,U,K',
    year: '2006',
    team: 'Italy / Juventus / Milan',
    difficulty: 1
  },
  {
    word: 'BUFFON',
    category: 'World Cup Legends',
    clue: 'Legendary Italian shot-stopper who conceded zero open-play goals in Italy\'s 2006 World Cup triumph.',
    masked_pattern: 'B _ F F _ N',
    missing_letters: 'U,O',
    distractors: 'A,E,I,R',
    year: '2006',
    team: 'Italy / Juventus',
    difficulty: 1
  },
  {
    word: 'SHEVCHENKO',
    category: 'Champions League Miracles',
    clue: 'Ukrainian goal machine who scored the winning 2003 Old Trafford UCL penalty for AC Milan.',
    masked_pattern: 'S H _ V C H _ N K O',
    missing_letters: 'E,E',
    distractors: 'A,I,O,U',
    year: '2003',
    team: 'AC Milan / Ukraine',
    difficulty: 2
  },
  {
    word: 'VAN BASTEN',
    category: 'World Cup Legends',
    clue: 'Dutch striker who scored the impossible acute-angle dipping volley in the Euro 1988 final.',
    masked_pattern: 'V _ N  B _ S T E N',
    missing_letters: 'A,A',
    distractors: 'E,I,O,U',
    year: '1988',
    team: 'Netherlands / AC Milan',
    difficulty: 2
  },
  {
    word: 'XAVI',
    category: 'World Cup Legends',
    clue: 'Master orchestrator of Tiki-Taka who provided two assists in the Euro 2012 final.',
    masked_pattern: 'X _ V _',
    missing_letters: 'A,I',
    distractors: 'E,O,U,T',
    year: '2010',
    team: 'Spain / Barcelona',
    difficulty: 1
  },
  {
    word: 'HENRY',
    category: 'World Cup Legends',
    clue: 'Arsenal\'s all-time record scorer known for his trademark Thierry Henry left-hand channel curler.',
    masked_pattern: 'H _ N R _',
    missing_letters: 'E,Y',
    distractors: 'A,O,I,U',
    year: '2004',
    team: 'Arsenal / France',
    difficulty: 1
  },
  {
    word: 'KLOSE',
    category: 'World Cup Legends',
    clue: 'All-time FIFA World Cup top scorer with 16 goals across four tournaments for Germany.',
    masked_pattern: 'K L _ S _',
    missing_letters: 'O,E',
    distractors: 'A,I,U,T',
    year: '2014',
    team: 'Germany',
    difficulty: 1
  },
  {
    word: 'ROONEY',
    category: 'Champions League Miracles',
    clue: 'Manchester United all-time top scorer famous for his stunning 2011 bicycle kick vs Man City.',
    masked_pattern: 'R _ _ N E Y',
    missing_letters: 'O,O',
    distractors: 'A,E,I,U',
    year: '2011',
    team: 'Manchester United',
    difficulty: 1
  },
  {
    word: 'NEYMAR',
    category: 'Champions League Miracles',
    clue: 'Brazilian superstar who scored twice and assisted the 95th-minute winner in La Remontada.',
    masked_pattern: 'N _ Y M _ R',
    missing_letters: 'E,A',
    distractors: 'I,O,U,T',
    year: '2017',
    team: 'Barcelona / Brazil',
    difficulty: 1
  },
  {
    word: 'HAALAND',
    category: 'Champions League Miracles',
    clue: 'Norwegian goal cyborg who shattered Premier League scoring records and won the 2023 treble.',
    masked_pattern: 'H _ _ L A N D',
    missing_letters: 'A,A',
    distractors: 'E,O,I,U',
    year: '2023',
    team: 'Manchester City',
    difficulty: 1
  },
  {
    word: 'RONALDINHO',
    category: 'World Cup Legends',
    clue: 'Samba magician who lobbed David Seaman from 40 yards at the 2002 World Cup in Shizuoka.',
    masked_pattern: 'R _ N _ L D _ N H O',
    missing_letters: 'O,A,I',
    distractors: 'E,U,T,S',
    year: '2002',
    team: 'Brazil / Barcelona',
    difficulty: 2
  },
  {
    word: 'MODRIC',
    category: 'World Cup Legends',
    clue: 'Croatian midfield maestro who won the 2018 Ballon d\'Or and led his nation to the World Cup final.',
    masked_pattern: 'M _ D R _ C',
    missing_letters: 'O,I',
    distractors: 'A,E,U,T',
    year: '2018',
    team: 'Croatia / Real Madrid',
    difficulty: 1
  },
  {
    word: 'CANNAVARO',
    category: 'World Cup Legends',
    clue: 'The Berlin Wall captain who won the 2006 Ballon d\'Or as a central defender for Italy.',
    masked_pattern: 'C _ N N _ V _ R O',
    missing_letters: 'A,A,A',
    distractors: 'E,I,O,U',
    year: '2006',
    team: 'Italy',
    difficulty: 2
  },
  {
    word: 'KEMPIS',
    category: 'World Cup Legends',
    clue: 'El Matador who scored twice in the 1978 World Cup final through a snowstorm of ticker tape in Buenos Aires.',
    masked_pattern: 'K _ M P _ S',
    missing_letters: 'E,E',
    distractors: 'A,O,I,U',
    year: '1978',
    team: 'Argentina',
    difficulty: 2
  },

  // 8. MORE ICONIC GROUNDS, HISTORIC SIDES & TACTICAL TERMS
  {
    word: 'STADE DE FRANCE',
    category: 'Historic Stadiums',
    clue: 'Saint-Denis arena where Zidane scored two headers against Brazil to win the 1998 World Cup.',
    masked_pattern: 'S T _ D E  D E  F R _ N C E',
    missing_letters: 'A,A',
    distractors: 'E,I,O,U',
    year: '1998',
    team: 'Paris, France',
    difficulty: 2
  },
  {
    word: 'MONUMENTAL',
    category: 'Historic Stadiums',
    clue: 'River Plate\'s fortress in Buenos Aires where Argentina won their first World Cup in 1978.',
    masked_pattern: 'M _ N _ M E N T _ L',
    missing_letters: 'O,U,A',
    distractors: 'E,I,R,T',
    year: '1978',
    team: 'Buenos Aires, Argentina',
    difficulty: 3
  },
  {
    word: 'ALLIANZ',
    category: 'Historic Stadiums',
    clue: 'Futuristic color-changing exterior stadium in Munich that hosted the 2012 Champions League final.',
    masked_pattern: 'A L L _ _ N Z',
    missing_letters: 'I,A',
    distractors: 'E,O,U,T',
    year: '2005',
    team: 'Bayern Munich',
    difficulty: 1
  },
  {
    word: 'HEYSEL',
    category: 'Historic Stadiums',
    clue: 'Brussels stadium where Juventus defeated Liverpool 1-0 in the tragic 1985 European Cup final.',
    masked_pattern: 'H _ Y S _ L',
    missing_letters: 'E,E',
    distractors: 'A,I,O,U',
    year: '1985',
    team: 'Brussels, Belgium',
    difficulty: 2
  },
  {
    word: 'DE KUIP',
    category: 'Historic Stadiums',
    clue: 'The Tub in Rotterdam where France defeated Italy with Trezeguet\'s golden goal in the Euro 2000 final.',
    masked_pattern: 'D _  K _ I P',
    missing_letters: 'E,U',
    distractors: 'A,O,R,T',
    year: '2000',
    team: 'Rotterdam, Netherlands',
    difficulty: 2
  },
  {
    word: 'MEAZZA',
    category: 'Historic Stadiums',
    clue: 'Official name of the San Siro stadium, honoring Italy\'s two-time World Cup winning forward.',
    masked_pattern: 'M _ _ Z Z A',
    missing_letters: 'E,A',
    distractors: 'I,O,U,R',
    year: '1980',
    team: 'Milan, Italy',
    difficulty: 2
  },
  {
    word: 'BICYCLE KICK',
    category: 'Tactics & Iconic Plays',
    clue: 'Acrobatic airborne strike where a player kicks the ball backwards over their head in mid-air.',
    masked_pattern: 'B _ C Y C L E  K _ C K',
    missing_letters: 'I,I',
    distractors: 'A,E,O,U',
    year: 'Skill',
    team: 'Iconic Strike',
    difficulty: 2
  },
  {
    word: 'SWEEPER',
    category: 'Tactics & Iconic Plays',
    clue: 'Defensive player situated behind the backline with freedom to clean up through balls.',
    masked_pattern: 'S W _ _ P E R',
    missing_letters: 'E,E',
    distractors: 'A,O,I,U',
    year: 'Tactic',
    team: 'Defensive Role',
    difficulty: 1
  },
  {
    word: 'LIBERO',
    category: 'Tactics & Iconic Plays',
    clue: 'Italian word meaning free, describing an attacking sweeper who steps into midfield.',
    masked_pattern: 'L _ B _ R O',
    missing_letters: 'I,E',
    distractors: 'A,O,U,T',
    year: 'Tactic',
    team: 'Tactical Role',
    difficulty: 2
  },
  {
    word: 'STOPPAGE',
    category: 'Tactics & Iconic Plays',
    clue: 'Added time at the end of each half to compensate for injuries and substitutions.',
    masked_pattern: 'S T _ P P _ G E',
    missing_letters: 'O,A',
    distractors: 'E,I,U,R',
    year: 'Rule',
    team: 'Match Clock',
    difficulty: 1
  },
  {
    word: 'GOLDEN GOAL',
    category: 'Trophies & Awards',
    clue: 'Sudden-death extra-time rule used in Euro 96, 2000 and the 1998/2002 World Cups.',
    masked_pattern: 'G _ L D E N  G _ _ L',
    missing_letters: 'O,O,A',
    distractors: 'E,I,U,T',
    year: 'Rule',
    team: 'Tournament Rule',
    difficulty: 2
  },
  {
    word: 'VAR',
    category: 'Tactics & Iconic Plays',
    clue: 'Video Assistant Referee introduced at the 2018 World Cup to review clear and obvious errors.',
    masked_pattern: 'V _ R',
    missing_letters: 'A',
    distractors: 'E,I,O,U',
    year: '2018',
    team: 'Modern Technology',
    difficulty: 1
  },

  // 9. ICONIC BALL-STRIKES & SIGNATURE SKILLS
  {
    word: 'SCORPION KICK',
    category: 'Tactics & Iconic Plays',
    clue: 'Acrobatic save performed by Colombian goalkeeper Rene Higuita at Wembley in 1995.',
    masked_pattern: 'S C _ R P _ O N  K _ C K',
    missing_letters: 'O,I,I',
    distractors: 'A,E,U,T',
    year: '1995',
    team: 'Rene Higuita',
    difficulty: 3
  },
  {
    word: 'ELASTICO',
    category: 'Tactics & Iconic Plays',
    clue: 'Flip-flap move pushing the ball outside then snapping it inside, perfected by Rivelino and Ronaldinho.',
    masked_pattern: 'E L _ S T _ C O',
    missing_letters: 'A,I',
    distractors: 'E,O,U,K',
    year: '1970',
    team: 'Signature Skill',
    difficulty: 2
  },
  {
    word: 'ROULETTE',
    category: 'Tactics & Iconic Plays',
    clue: 'The 360-degree pirouette drag-back turn made famous across Europe by Zinedine Zidane.',
    masked_pattern: 'R _ _ L E T T E',
    missing_letters: 'O,U',
    distractors: 'A,E,I,S',
    year: 'Skill',
    team: 'Zidane Pirouette',
    difficulty: 2
  },
  {
    word: 'TRIVELA',
    category: 'Tactics & Iconic Plays',
    clue: 'Bending shot or cross struck with the outside of the boot, masterfully executed by Ricardo Quaresma.',
    masked_pattern: 'T R _ V _ L A',
    missing_letters: 'I,E',
    distractors: 'A,O,U,R',
    year: 'Skill',
    team: 'Outside Boot',
    difficulty: 2
  },
  {
    word: 'STEP OVER',
    category: 'Tactics & Iconic Plays',
    clue: 'Feinting move where a player circles their feet over the ball without touching it to deceive defenders.',
    masked_pattern: 'S T _ P  _ V E R',
    missing_letters: 'E,O',
    distractors: 'A,I,U,T',
    year: 'Skill',
    team: 'Signature Feint',
    difficulty: 1
  },
  {
    word: 'KNUCKLEBALL',
    category: 'Tactics & Iconic Plays',
    clue: 'Erratic free-kick technique with zero ball spin popularized by Juninho Pernambucano and Cristiano Ronaldo.',
    masked_pattern: 'K N _ C K L _ B _ L L',
    missing_letters: 'U,E,A',
    distractors: 'I,O,T,S',
    year: 'Skill',
    team: 'Free Kick',
    difficulty: 3
  },

  // 10. EXPANDED HISTORIC LEGENDS
  {
    word: 'BECKHAM',
    category: 'Champions League Miracles',
    clue: 'Dead-ball specialist whose stoppage-time free-kick against Greece sent England to the 2002 World Cup.',
    masked_pattern: 'B _ C K H _ M',
    missing_letters: 'E,A',
    distractors: 'I,O,U,R',
    year: '2001',
    team: 'England / Man United',
    difficulty: 1
  },
  {
    word: 'KAHN',
    category: 'World Cup Legends',
    clue: 'Der Titan, fiery German goalkeeper who was awarded the Golden Ball at the 2002 World Cup.',
    masked_pattern: 'K _ H N',
    missing_letters: 'A',
    distractors: 'E,I,O,U',
    year: '2002',
    team: 'Germany / Bayern',
    difficulty: 1
  },
  {
    word: 'ROBERTO CARLOS',
    category: 'World Cup Legends',
    clue: 'Thunderous left-back who scored the physics-defying 40-yard banana free-kick against France in 1997.',
    masked_pattern: 'R _ B E R T O  C _ R L _ S',
    missing_letters: 'O,A,O',
    distractors: 'E,I,U,T',
    year: '1997',
    team: 'Brazil / Real Madrid',
    difficulty: 2
  },
  {
    word: 'TOTTI',
    category: 'World Cup Legends',
    clue: 'Il Capitano, one-club king who spent his entire 25-year career at AS Roma and won the 2006 World Cup.',
    masked_pattern: 'T _ T T _',
    missing_letters: 'O,I',
    distractors: 'A,E,U,R',
    year: '2006',
    team: 'Italy / AS Roma',
    difficulty: 1
  },
  {
    word: 'DEL PIERO',
    category: 'World Cup Legends',
    clue: 'Juventus icon whose curling finish in the 121st minute sealed Germany\'s fate in Dortmund 2006.',
    masked_pattern: 'D _ L  P _ _ R O',
    missing_letters: 'E,I,E',
    distractors: 'A,O,U,T',
    year: '2006',
    team: 'Italy / Juventus',
    difficulty: 2
  },
  {
    word: 'CANTONA',
    category: 'Champions League Miracles',
    clue: 'The King of Old Trafford with the upturned collar who transformed Manchester United in the 1990s.',
    masked_pattern: 'C _ N T _ N A',
    missing_letters: 'A,O',
    distractors: 'E,I,U,S',
    year: '1995',
    team: 'Manchester United',
    difficulty: 2
  },
  {
    word: 'SCHOLES',
    category: 'Champions League Miracles',
    clue: 'Ginger midfield maestro whose 25-yard thunderbolt against Barcelona sent Man United to Moscow in 2008.',
    masked_pattern: 'S C H _ L _ S',
    missing_letters: 'O,E',
    distractors: 'A,I,U,R',
    year: '2008',
    team: 'Manchester United',
    difficulty: 2
  },
  {
    word: 'GIGGS',
    category: 'Champions League Miracles',
    clue: 'Welsh wizard who scored the greatest solo FA Cup goal against Arsenal in 1999 and won 13 Premier Leagues.',
    masked_pattern: 'G _ G G _',
    missing_letters: 'I,S',
    distractors: 'A,E,O,T',
    year: '1999',
    team: 'Manchester United',
    difficulty: 1
  },
  {
    word: 'ETO O',
    category: 'Champions League Miracles',
    clue: 'Cameroonian striker who won consecutive historic trebles with Barcelona (2009) and Inter (2010).',
    masked_pattern: 'E T _  _',
    missing_letters: 'O,O',
    distractors: 'A,E,I,U',
    year: '2010',
    team: 'Cameroon / Inter',
    difficulty: 1
  },
  {
    word: 'SUAREZ',
    category: 'World Cup Legends',
    clue: 'El Pistolero whose controversial 120th-minute handball against Ghana saved Uruguay at the 2010 World Cup.',
    masked_pattern: 'S _ _ R E Z',
    missing_letters: 'U,A',
    distractors: 'E,I,O,T',
    year: '2010',
    team: 'Uruguay / Barcelona',
    difficulty: 2
  },
  {
    word: 'LEWANDOWSKI',
    category: 'Champions League Miracles',
    clue: 'Polish predator who famously scored 5 goals in 9 minutes as a substitute for Bayern Munich in 2015.',
    masked_pattern: 'L _ W _ N D _ W S K I',
    missing_letters: 'E,A,O',
    distractors: 'I,U,R,T',
    year: '2015',
    team: 'Poland / Bayern',
    difficulty: 3
  },
  {
    word: 'BENZEMA',
    category: 'Champions League Miracles',
    clue: '2022 Ballon d\'Or winner whose hat-tricks against PSG and Chelsea led Real Madrid to the 14th UCL crown.',
    masked_pattern: 'B _ N Z _ M A',
    missing_letters: 'E,E',
    distractors: 'A,I,O,U',
    year: '2022',
    team: 'Real Madrid / France',
    difficulty: 1
  },
  {
    word: 'SALAH',
    category: 'Champions League Miracles',
    clue: 'Egyptian King who broke the 38-game Premier League scoring record and won the 2019 Champions League.',
    masked_pattern: 'S _ L _ H',
    missing_letters: 'A,A',
    distractors: 'E,I,O,U',
    year: '2019',
    team: 'Liverpool / Egypt',
    difficulty: 1
  },
  {
    word: 'JAIRZINHO',
    category: 'World Cup Legends',
    clue: 'The Hurricane who scored in every single match of Brazil\'s glorious 1970 World Cup campaign.',
    masked_pattern: 'J _ _ R Z I N H O',
    missing_letters: 'A,I',
    distractors: 'E,O,U,T',
    year: '1970',
    team: 'Brazil / Botafogo',
    difficulty: 3
  },
  {
    word: 'RIVELINO',
    category: 'World Cup Legends',
    clue: 'Mustachioed Brazilian maestro famous for his atomic kick free-kicks and inventing the elastico in 1970.',
    masked_pattern: 'R _ V _ L I N O',
    missing_letters: 'I,E',
    distractors: 'A,O,U,S',
    year: '1970',
    team: 'Brazil / Corinthians',
    difficulty: 2
  },
  {
    word: 'TAFFAREL',
    category: 'World Cup Legends',
    clue: 'Brazilian goalkeeper whose shootout heroics in the 1994 final and 1998 semifinal entered legend.',
    masked_pattern: 'T _ F F _ R _ L',
    missing_letters: 'A,A,E',
    distractors: 'I,O,U,S',
    year: '1994',
    team: 'Brazil',
    difficulty: 2
  },
  {
    word: 'BATISTUTA',
    category: 'World Cup Legends',
    clue: 'Batigol, explosive Argentine number 9 who scored hat-tricks in two separate World Cups (1994 and 1998).',
    masked_pattern: 'B _ T _ S T _ T A',
    missing_letters: 'A,I,U',
    distractors: 'E,O,R,K',
    year: '1998',
    team: 'Argentina / Fiorentina',
    difficulty: 2
  },
  {
    word: 'KLINSMANN',
    category: 'World Cup Legends',
    clue: 'Diving header expert who won the 1990 World Cup with Germany and popularized the diving celebration.',
    masked_pattern: 'K L _ N S M _ N N',
    missing_letters: 'I,A',
    distractors: 'E,O,U,R',
    year: '1990',
    team: 'Germany',
    difficulty: 2
  },
  {
    word: 'STOICHKOV',
    category: 'World Cup Legends',
    clue: 'The Dagger, Bulgarian firebrand who won the 1994 World Cup Golden Boot and the Ballon d\'Or.',
    masked_pattern: 'S T _ _ C H K O V',
    missing_letters: 'O,I',
    distractors: 'A,E,U,R',
    year: '1994',
    team: 'Bulgaria / Barcelona',
    difficulty: 3
  },
  {
    word: 'DESCHAMPS',
    category: 'World Cup Legends',
    clue: 'The Water Carrier who captained France to 1998 victory and managed them to the 2018 World Cup title.',
    masked_pattern: 'D _ S C H _ M P S',
    missing_letters: 'E,A',
    distractors: 'I,O,U,T',
    year: '1998',
    team: 'France',
    difficulty: 2
  },
  {
    word: 'CARLOS ALBERTO',
    category: 'World Cup Legends',
    clue: 'Captain who completed Brazil\'s 1970 8-pass masterwork by blasting the fourth goal into the bottom corner.',
    masked_pattern: 'C _ R L O S  _ L B E R T O',
    missing_letters: 'A,A',
    distractors: 'E,I,O,U',
    year: '1970',
    team: 'Brazil',
    difficulty: 2
  },
  {
    word: 'ESTADIO DA LUZ',
    category: 'Historic Stadiums',
    clue: 'Stadium of Light in Lisbon where Real Madrid secured La Decima in 2014 with Ramos\'s 93rd-minute header.',
    masked_pattern: 'E S T _ D I O  D _  L U Z',
    missing_letters: 'A,A',
    distractors: 'E,I,O,U',
    year: '2014',
    team: 'Benfica / Lisbon',
    difficulty: 2
  }
];

module.exports = { SEED_WORDS };


